
apiVersion: apps/v1
kind: Deployment
metadata:
     name: myjenkins
spec:
   replicas: 2
   selector:
      matchLabels:
            app: jenkinskubernetes
   template:
       metadata:
           labels:
              app: jenkinskubernetes
       spec: 
         containers:
             - name: flaskk8s
               image: rtxverma123/flaskkubernetes
               ports:
                 - containerPort: 8080
         imagePullPolicy: Always
